init: Исходные данные: {
  obor: Оборачиваемость: {
    pile: Запасы готовой продукции
    export_sell_period: период поступления от экспортных продаж
  }
  target_deductions: Отчисления в целевые фонды {
     SSP: единый социальный платеж
  }
}
